### ISSUE TITLE
I am using your project for...

### ISSUE THREAD

**Issue by furtabs** [albino/wwwcats#20]
I just want to tell you i am using your project for a tournament our family is doing. I tried to improve some of the CSS and feel free to pull in anything upstream. Great work you are doing and thanks for selecting a semi-open license.

**Comment by albino** [comment]
Hello!

Thanks for letting me know, I am glad you are enjoying it. If you have any questions, please feel free to ask.

The AGPLv3 is actually a fully open-source license: https://opensource.org/licenses/AGPL-3.0

However, your website is not currently compliant with it - nor would it be with any of the other major open-source licenses, as you are distributing my JavaScript without giving me credit. Please see the email I sent you for more information.

By law, you have to do this even if the website isn't accessible to the public - but there's obviously no real way of me knowing, or caring. But if it's going to be accessible to the public, I would ask that you give me fair attribution.

All the best. Happy playing!
